POST http://127.0.0.1:8000/api/auth/register
Content-Type: application/json
X-Device: IntelliJ Test

{
    "email": "test@example.com",
    "password": "Password123!",
    "firstName": "Test",
    "lastName": "User",
    "device": "IntelliJ Test"
}