# src/main/resources/application.conf
jwt {
  issuer = "http://localhost:8080"
  audience = "momento-clients-dev"

  # default for local dev:
  secret = "dev-secret"
  # override if env variable is present:
  secret = ${?JWT_SECRET}

  accessTtlSeconds  = 900        # 15m
  refreshTtlSeconds = 2592000    # 30d
}

ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [ ApplicationKt.module ]
  }
}
