# src/main/resources/application.conf
jwt {
  issuer  = "https://momento.app"
  audience = "momento-clients"
}

ktor {
  deployment {
    # default first…
    port = 8080
    # …then allow environment to override if set
    port = ${?PORT}
  }
  application {
    modules = [ com.example.ApplicationKt.module ]
  }
}
